name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd server/
        make install-dev

    - name: Lint with Ruff
      run: |
        ruff check server/

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd server/
        make install-dev

    - name: Run tests
      env:
        MONGO_URI: mongodb://mongodb:27017/chat-mongodb
      run: |
        cd server/
        export PYTHONPATH=$PYTHONPATH:./src
        pytest tests/
